apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dummy
  labels:
    app: argocd-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: platform-argocd
      app.kubernetes.io/name: argocd-dummy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: platform-argocd
        app.kubernetes.io/name: argocd-dummy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: role
                    operator: In
                    values:
                      - management
      containers:
      - name: argocd-dummy
        image: pog-dev-registry.cloudzcp.io/earth1223/argodummy:develop
        env:
        - name: foo
          value: var2
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        imagePullPolicy: Always
        readinessProbe:
          failureThreshold: 10 
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:  
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
  strategy:
    type: RollingUpdate
